apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-docker-deployment
  labels:
    app: spring-petclinic-docker
spec:
  replicas: #$numberOfReplicas$#
  selector:
    matchLabels:
       app: spring-petclinic-docker
  template:
    metadata:
       labels:
         app: spring-petclinic-docker
    spec:
       containers:
         - name: spring-petclinic-docker
           image: 460606100227.dkr.ecr.ap-southeast-1.amazonaws.com/awsbg:latest
           ports:
             - containerPort: 8080