apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-docker-service
spec:
  type: LoadBalancer
  selector:
    app: spring-petclinic-docker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80